module.exports = {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        bug: "#A0AF19",
        dark: "#4F3C2D",
        dragon: "#725BDC",
        ice: "#6FD3F4",
        grass: "#65B52E",
        fire: "#C72200",
        electric: "#FBB613",
        fighting: "#762E1A",
        fairy: "#EDAAEC",
        ghost: "#52549D",
        steel: "#9191A1",
        poison: "#944695",
        water: "#0C69C0",
        normal: "#C6BFB7",
        flying: "#5D74D5",
        ground: "#CFAF55",
        psychic: "#E33A73",
        rock: "#9D883D",
        test: "#FBBF24",
      },
      screens: {
        'h-sm': { raw: '(max-height: 480px)' },
        'h-md': { raw: '(min-height: 600px)' },
        'h-lg': { raw: '(min-height: 768px)' },
        'h-xl': { raw: '(min-height: 960px)' },
        'h-2xl': { raw: '(min-height: 1080px)' },
        'h-3xl': { raw: '(min-height: 1600px)' },
      },
    },
  },
  plugins: [],
}